version: '3'

services:

  pgsql:
    image: postgres:alpine
    container_name: pgsql
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: taskifydb
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
      
  backend:
    build: ./backend
    container_name: backend-taskify
    ports:
      - "3000:3000"
    depends_on:
      - pgsql
    environment:
      DATABASE_URL: postgres://pguser:pgpassword@pgsql:5432/taskifydb
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend-taskify
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    restart: always

  

volumes:
  pg-data:
